### ISSUE TITLE
GeometryCustomPreview sample seems like just the basic nodeModel sample.

### ISSUE THREAD

**Issue by mjkkirschner** [nonoesp/DynamoNodeModelsEssentials#1]

**Comment by nonoesp** [comment]
Hi! It is actually really similar. The difference is that the output is a `MyMesh` object, which has a custom `Tessellate` method, defined in [NodeModelsEssentialsFunctions.cs](https://github.com/nonoesp/DynamoNodeModelsEssentials/blob/master/src/Essentials/NodeModelsEssentialsFunctions/NodeModelsEssentialsFunctions.cs#L217-L282).

I just added this to the summary of the node.
